version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-app
        volumes:
            - ./app:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - db
            - redis

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-nginx
        # restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - app

    db:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-db
        # restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=backend-admin-video-catalog
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - backend-admin-video-catalog-network

    elasticsearch:
        build:
            context: ./docker/elasticsearch
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-elasticsearch
        # restart: always
        volumes:
            - ./docker/elasticsearchdata:/var/lib/elasticsearch/data/  
        environment:
            ES_JAVA_OPTS: '-Xmx256m -Xms256m'
            discovery.type: 'single-node'
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend-admin-video-catalog-network

    logstash:
        build:
            context: ./docker/logstash
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-logstash
        # restart: always
        volumes:
            - ./docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
        command: logstash -f /etc/logstash/conf.d/logstash.conf -r
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        ports:
            - "9600:9600"
            - "8082:8082"
            - "4718:4718/udp"
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - elasticsearch

    kibana:
        build:
            context: ./docker/kibana
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-kibana
        # restart: always
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - "5601:5601"
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - elasticsearch

    redis:
        image: redis:alpine
        container_name: backend-admin-video-catalog-redis
        networks:
            - backend-admin-video-catalog-network

    keycloak:
        build:
            context: ./docker/keycloak
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-keycloak
        ports:
            - "8081:8080"
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=mysql            
            - KC_DB_USERNAME=root
            - KC_DB_PASSWORD=root
            - KC_DB_URL_HOST=db
            - KC_DB_URL_PORT=3306
            - KC_DB_SCHEMA=keycloak
        command:
            [ "start-dev"]
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - db

networks:
    backend-admin-video-catalog-network:
        driver: bridge
    elk:
        driver: bridge
    