version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-app
        volumes:
            - ./app:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - db
            - redis

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - app

    db:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=backend-admin-video-catalog
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - backend-admin-video-catalog-network

    redis:
        image: redis:alpine
        container_name: backend-admin-video-catalog-redis
        networks:
            - backend-admin-video-catalog-network

networks:
    backend-admin-video-catalog-network:
        driver: bridge